# Generated by Django 5.0.6 on 2024-06-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp indicating when the model instance wasinitially added or created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='address',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp representing the most recent update ormodification to the model instance.', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp indicating when the model instance wasinitially added or created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp representing the most recent update ormodification to the model instance.', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp indicating when the model instance wasinitially added or created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp representing the most recent update ormodification to the model instance.', verbose_name='Modified at'),
        ),
    ]
