# Generated by Django 5.0.6 on 2024-06-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_address_created_alter_address_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(max_length=1024, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=225, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=225, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=225, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=225, verbose_name='ZIP Code'),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='economical_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Economical Code'),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='national_code',
            field=models.IntegerField(unique=True, verbose_name='National Code'),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='phone',
            field=models.IntegerField(unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='corporateprofile',
            name='register_number',
            field=models.IntegerField(unique=True, verbose_name='Register Number'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='first_name',
            field=models.CharField(max_length=1024, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='job',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='last_name',
            field=models.CharField(max_length=1024, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='national_code',
            field=models.CharField(max_length=1024, unique=True, verbose_name='National Code'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='phone',
            field=models.IntegerField(unique=True, verbose_name='Phone'),
        ),
    ]
