# Generated by Django 5.0.6 on 2024-06-17 17:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='height',
        ),
        migrations.RemoveField(
            model_name='productgallery',
            name='width',
        ),
        migrations.AddField(
            model_name='productgallery',
            name='height_field',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text="size of picture's Height", null=True, verbose_name='Picture Height'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='slug',
            field=models.SlugField(help_text="A URL-friendly version of the title, typically used inthe URL to identify the content's location.", max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='title',
            field=models.CharField(help_text='The main textual identifier or name for the content', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='width_field',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text="size of picture's Width", null=True, verbose_name='Picture Width'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp indicating when the model instance wasinitially added or created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp representing the most recent update ormodification to the model instance.', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp indicating when the model instance wasinitially added or created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp representing the most recent update ormodification to the model instance.', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(help_text="A URL-friendly version of the title, typically used inthe URL to identify the content's location.", max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(help_text='The main textual identifier or name for the content', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp indicating when the model instance wasinitially added or created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp representing the most recent update ormodification to the model instance.', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text="A URL-friendly version of the title, typically used inthe URL to identify the content's location.", max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='The main textual identifier or name for the content', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp indicating when the model instance wasinitially added or created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='description',
            field=models.TextField(blank=True, help_text="A textual explanation or summary providing additionalinformation about the item's characteristics or purpose.", null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp representing the most recent update ormodification to the model instance.', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='sku',
            field=models.UUIDField(default=uuid.uuid4, help_text='A unique identifier assigned to each product in inventory.', unique=True, verbose_name='Stock of Unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp indicating when the model instance wasinitially added or created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp representing the most recent update ormodification to the model instance.', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.UUIDField(default=uuid.uuid4, help_text='A unique identifier assigned to each product in inventory.', unique=True, verbose_name='Stock of Unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text="A URL-friendly version of the title, typically used inthe URL to identify the content's location.", max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='The main textual identifier or name for the content', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='alternate_text',
            field=models.CharField(blank=True, help_text='Describe about picture that is uploaded. Please write a good description for search engines.', max_length=110, null=True, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(3)], verbose_name='Alternate Text'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp indicating when the model instance wasinitially added or created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp representing the most recent update ormodification to the model instance.', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp indicating when the model instance wasinitially added or created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp representing the most recent update ormodification to the model instance.', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text="A URL-friendly version of the title, typically used inthe URL to identify the content's location.", max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(help_text='The main textual identifier or name for the content', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
    ]
