# Generated by Django 5.0.6 on 2024-06-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_productgallery_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='warehouse.product', verbose_name='Related Products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suggested_products',
            field=models.ManyToManyField(blank=True, to='warehouse.product', verbose_name='Suggested Products'),
        ),
    ]
