# Generated by Django 5.0.6 on 2024-06-17 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='Province')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('postal_address', models.TextField(verbose_name='Postal Address')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('house_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='House Number')),
                ('building_unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Building Unit')),
                ('footnote', models.TextField(blank=True, null=True, verbose_name='Footnote')),
                ('receiver_first_name', models.CharField(max_length=255, verbose_name='Receiver First Name')),
                ('receiver_last_name', models.CharField(max_length=255, verbose_name='Receiver Last Name')),
                ('receiver_phone_number', models.CharField(max_length=20, verbose_name='Receiver Phone Number')),
                ('receiver_national_code', models.CharField(max_length=20, verbose_name='Receiver National Code')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
            options={
                'verbose_name': 'Order Address',
                'verbose_name_plural': 'Order Addresses',
                'db_table': 'basket_orderaddresses',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'basket_cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='Cart')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='warehouse.pack', verbose_name='Pack')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'basket_cartitem',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=255, unique=True, verbose_name='Transaction Number')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('packing', 'Packing'), ('cargo_line', 'Cargo Line'), ('sent', 'Sent'), ('delivered', 'Delivered')], default='submitted', max_length=50, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart', verbose_name='Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('order_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderaddress', verbose_name='Order Address')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'basket_orders',
            },
        ),
    ]
