# Generated by Django 5.0.6 on 2024-06-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='slug',
            field=models.SlugField(help_text="A URL-friendly version of the title, typically used inthe URL to identify the content's location.", max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp indicating when the model instance wasinitially added or created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp representing the most recent update ormodification to the model instance.', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp indicating when the model instance wasinitially added or created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp representing the most recent update ormodification to the model instance.', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp indicating when the model instance wasinitially added or created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp representing the most recent update ormodification to the model instance.', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp indicating when the model instance wasinitially added or created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp representing the most recent update ormodification to the model instance.', verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='title',
            field=models.CharField(help_text='The main textual identifier or name for the content', max_length=255, null=True, unique=True, verbose_name='Title'),
        ),
    ]
