# Generated by Django 5.0.6 on 2024-06-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderaddress_slug_alter_cart_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='house_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='House Number'),
        ),
    ]
