# Generated by Django 5.0.6 on 2024-06-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orderaddress_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='building_unit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Building Unit'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='receiver_first_name',
            field=models.CharField(verbose_name='Receiver First Name'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='receiver_last_name',
            field=models.CharField(verbose_name='Receiver Last Name'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='receiver_national_code',
            field=models.IntegerField(verbose_name='Receiver National Code'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='receiver_phone_number',
            field=models.IntegerField(verbose_name='Receiver Phone Number'),
        ),
    ]
